version: 2
registries:
  stephane:
    type: python-index
    url: https://us-west1-python.pkg.dev/personal-313102/stephane/
    username: _json_key_base64
    password: ${{secrets.TOKEN_STEPHANE_REPO}}
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - stephane
    schedule:
      interval: "daily"
