[project]
name = "esovalue"
version = "0.1.15"
description = "Valuation of employee stock options"
readme = "README.md"
authors = [{ name = "Stéphane Thibaud", email = "snthibaud@gmail.com" }]
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "mpmath",
]

[project.urls]
repository = "https://github.com/snthibaud/esovalue"
"ESO valuation app" = "https://eso.stephanethibaud.xyz/"

[dependency-groups]
dev = [
    "hypothesis",
    "pytest>=8.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
