[project]
name = "esovalue"
version = "0.1.15"
description = "Valuation of employee stock options"
readme = "README.md"
authors = [{ name = "Stéphane Thibaud", email = "snthibaud@gmail.com" }]
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "mpmath",
]

[project.urls]
repository = "https://github.com/snthibaud/esovalue"
"ESO valuation app" = "https://eso.stephanethibaud.xyz/"

[dependency-groups]
dev = [
    "hypothesis",
    "pytest",
    "pytest-xdist",
    "hvplot",
    "networkx",
    "scipy>1.6.1",
    "notebook>=6.4.12",
    "jupyter~=1.0",
    "nbconvert>=6.3",
    "jupyter-core>=4.11.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
